// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Index": {
    "title": "Home",
    "loggedIn": "Logged in as {username}",
    "loggedOut": "You are logged out.",
    "login": "Login",
    "logout": "Logout",
    "secret": "Secret page for logged in users"
  },
  "LocaleLayout": {
    "title": "Next Scaffold",
    "home": "Home",
    "posts": "Posts",
    "logout": "Logout",
    "login": "Login"

  },
  "Login": {
    "title": "Login",
    "username": "Username",
    "password": "Password",
    "submit": "Login",
    "error": "{error, select, CredentialsSignin {Invalid username or password} other {Unknown error}}",
    "signInWithGoogle": "Sign in with Google"
  },
  "LocaleSwitcher": {
    "switchLocale": "Switch to {locale, select, ar {Arabic} en {English} other {Unknown}}"
  },

  "PostsPage":{
    "title":"All Posts",
  "noPosts": "No posts yet.",
    "loadError": "Failed to load posts",
    "loadMore":"Load more",
  "goToPage": "Go to page {page}",
  "previous": "Previous",
  "next": "Next",
  "pageInfo": "Page {current} of {total}",
  "titlePlaceholder": "Enter post title",
"createTitle": "Create a New Post",
  "contentPlaceholder": "Write your content here...",
  "createButton": "Create Post",
  "creating": "Creating...",
  "createSuccess": "Post created successfully!",
  "createError": "Failed to create post.",
  "postsList": "All Posts",
  "loadingPosts": "Loading posts"
  },
  "CreatePostPage": {
  "title": "Create a New Post",
  "titlePlaceholder": "Enter post title",
"createTitle": "Create a New Post",
    "postsTitle": "All Posts",
  "contentPlaceholder": "Write your content here...",
  "createButton": "Create Post",
  "creating": "Creating...",
  "createSuccess": "Post created successfully!",
  "createError": "Failed to create post.",
  "postsList": "All Posts",
  "loadingPosts": "Loading posts",
  "noPosts": "No posts yet."
}

};
export default messages;