// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Index": {
    "title": "Home",
    "loggedIn": "Logged in as {username}",
    "loggedOut": "You are logged out.",
    "login": "Login",
    "logout": "Logout",
    "secret": "Secret page for logged in users"
  },
  "LocaleLayout": {
    "title": "next-intl with Auth.js example",
    "home": "Home",
    "posts": "Posts",
    "createPost": "Create Post"
  },
  "Login": {
    "title": "Login",
    "username": "Username",
    "password": "Password",
    "submit": "Login",
    "error": "{error, select, CredentialsSignin {Invalid username or password} other {Unknown error}}"
  },
  "LocaleSwitcher": {
    "switchLocale": "Switch to {locale, select, ar {Arabic} en {English} other {Unknown}}"
  },
  "Secret": {
    "title": "Secret page",
    "description": "This page is only visible for logged in users."
  },

  "PostsPage":{
    "title":"Posts",
    "noPosts":"no posts",

  "titlePlaceholder": "Enter post title",
"createTitle": "Create a New Post",
    "postsTitle": "All Posts",
  "contentPlaceholder": "Write your content here...",
  "createButton": "Create Post",
  "creating": "Creating...",
  "createSuccess": "Post created successfully!",
  "createError": "Failed to create post.",
  "postsList": "All Posts",
  "loadingPosts": "Loading posts"
  },
  "CreatePostPage": {
  "title": "Create a New Post",
  "titlePlaceholder": "Enter post title",
"createTitle": "Create a New Post",
    "postsTitle": "All Posts",
  "contentPlaceholder": "Write your content here...",
  "createButton": "Create Post",
  "creating": "Creating...",
  "createSuccess": "Post created successfully!",
  "createError": "Failed to create post.",
  "postsList": "All Posts",
  "loadingPosts": "Loading posts",
  "noPosts": "No posts yet."
}

};
export default messages;