// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Index": {
    "title": "Home",
    "loggedIn": "Logged in as {username}",
    "loggedOut": "You are logged out.",
    "login": "Login",
    "logout": "Logout",
    "secret": "Secret page for logged in users"
  },
  "LocaleLayout": {
    "title": "next-intl with Auth.js example",
    "home": "Home",
    "posts": "Posts",
    "createPost": "Create Post"
  },
  "Login": {
    "title": "Login",
    "username": "Username",
    "password": "Password",
    "submit": "Login",
    "error": "{error, select, CredentialsSignin {Invalid username or password} other {Unknown error}}"
  },
  "LocaleSwitcher": {
    "switchLocale": "Switch to {locale, select, ar {Arabic} en {English} other {Unknown}}"
  },
  "Secret": {
    "title": "Secret page",
    "description": "This page is only visible for logged in users."
  },

  "PostsPage":{
    "title":"posts",
    "noPosts":"no posts"
  },
  "CreatePostPage": {
    "title": "Create New Post",
    "titlePlaceholder": "Post Title",
    "contentPlaceholder": "Post Content",
    "createButton": "Create Post",
    "creating": "Creating...",
    "successMessage": "Post created successfully!",
    "failureMessage": "Failed to create post."
  }



};
export default messages;